### ISSUE TITLE
Can somebody tell me what's the value read from the color sensor

### ISSUE THREAD

**Issue by x1zbin** [sparkfun/APDS-9960_RGB_and_Gesture_Sensor#12]
I run the Colorsensor example ,but the value read form it is more then 255,it's very big.
What the data mean read from the color sensor.isn't it mean the RGB vlue in ambient light?
Who can tell me the answer?

**Comment by ShawnHymel** [comment]
The values from color sensor can be 0 to 65535, as it's a 16 bit value. Try shining different colored light into the sensor to see if the value changes.
