### ISSUE TITLE
Gesture Sensor Interrupt Frozen on 8266?

### ISSUE THREAD

**Issue by beachmiles** [sparkfun/APDS-9960_RGB_and_Gesture_Sensor#18]
On a wemos mini I think I am getting INT lockups for the gesture sensor. 
I am still getting brightness readings over i2c ok.

It seems like the swipe works good for the first 15-30 swipes but then will stop working, or if I leave it running overnight in the morning the gesture sensor no longer activates.

I put a 2 second timeout in the apds.readGesture() function to try an avoid lockups if an object gets placed in front of the sensor but that didnt help.

**Comment by AndyEngland521** [comment]
Can you please provide your code?
