### ISSUE TITLE
Multiple troubles with the readings

### ISSUE THREAD

**Issue by albydnc** [sparkfun/APDS-9960_RGB_and_Gesture_Sensor#19]
I have bought an apds9960 sensor and attached it to my MKR1000 board. The library is saying initialization complete but then proximity readings are always 0. the Color Sensor and Ambient light examples are working but the readings of green and blue are wrong (-1, 0). What could be the problem? thanks.
I was thinking is a problem with the IR led.

**Comment by loricrotser** [comment]
Hi! Apologies for the long delay in response, I was just assigned this. 

I don't have a 1000 in house, but I did just test it with the MKR Vidor 4000. I didn't see any issues - all my proximity readings came through as expected. Maybe try double checking the pin connections? 

If you still need help, I'd recommend hopping onto the [SparkFun forums](https://forum.sparkfun.com/index.php) to see if tech support can dig in a little further. The issues here are more for code and library bugs, hence the long reply time. 

Hope this is helpful!
