### ISSUE TITLE
Function "disableProximitySensor()" is unimplemented.

### ISSUE THREAD

**Issue by jmg5150** [sparkfun/APDS-9960_RGB_and_Gesture_Sensor#2]
bool disableProximitySensor() function is not implemented, calling it results in compile error. See line 342 of SparkFun_APDS9960.cpp.

The following function definition should give it the proper functionality.

/**
* @brief Ends the Proximity sensor on the APDS-9960
*
* @return True if sensor disabled correctly. False on error.
*/
bool SparkFun_APDS9960::disableProximitySensor()
{
	if (!setProximityIntEnable(0)) {
		return false;
	}
	if (!setMode(PROXIMITY, 0)) {
		return false;
	}

	return true;
}

**Comment by ShawnHymel** [comment]
Copied to library and pushed back to GitHub. Thanks for the fix!
