### ISSUE TITLE
Copy a color to RGB LED (KY09 RGB LED SMD Tri Color Module) using APDS9960 RGB color sensor

### ISSUE THREAD

**Issue by armak1983-2018** [sparkfun/APDS-9960_RGB_and_Gesture_Sensor#22]
i am using the following sketch to copy color to RGB LED using APDS9960 RGB sensor. 

the sketch was uploaded successfully, but the LED is not working when color is put in front of the sensor!

#include <Wire.h>
#include "Adafruit_APDS9960.h"
Adafruit_APDS9960 apds;

#define redpin 3
#define greenpin 5
#define bluepin 6

#define commonAnode false

byte gammatable[256];

void setup() {
  Serial.begin(9600);
  Serial.println("Color View Test!");

  if (apds.begin()) {
    Serial.println("Found sensor");
  } else {
    Serial.println("No TCS34725 found ... check your connections");
    while (1); // halt!
  }
  
  
  pinMode(redpin, OUTPUT);
  pinMode(greenpin, OUTPUT);
  pinMode(bluepin, OUTPUT);
  

  for (int i=0; i<256; i++) {
    float x = i;
    x /= 255;
    x = pow(x, 2.5);
    x *= 255;
      
    if (commonAnode) {
      gammatable[i] = 255 - x;
    } else {
      gammatable[i] = x;      
    }
    //Serial.println(gammatable[i]);
  }
}

void loop() {
  //create some variables to store the color data in
  uint16_t clear, red, green, blue;
  
  //wait for color data to be ready
  while(!apds.colorDataReady()){
    delay(5);
  }

  //get the data and print the different channels
  apds.getColorData(&red, &green, &blue, &clear);
  Serial.print("red: ");
  Serial.print(red);
  
  Serial.print(" green: ");
  Serial.print(green);
  
  Serial.print(" blue: ");
  Serial.print(blue);
  
  Serial.print(" clear: ");
  Serial.println(clear);
  Serial.println();
  
  delay(1000);
   // Figure out some basic hex code for visualization
  uint32_t sum = clear;
  float r, g, b;
  r = red; r /= sum;
  g = green; g /= sum;
  b = blue; b /= sum;
  red *= 256; green *= 256; blue *= 256;
  Serial.print("\t");
  Serial.print((int)r, HEX); Serial.print((int)g, HEX); Serial.print((int)b, HEX);
  Serial.println();

  analogWrite(redpin, gammatable[(int)r]);
  analogWrite(greenpin, gammatable[(int)g]);
  analogWrite(bluepin, gammatable[(int)b]);
}

**Comment by nseidle** [comment]
Hi - Looks like you're using the adafruit library? Sorry, but we can't help much. You should give the [SparkFun library](https://github.com/sparkfun/SparkFun_APDS-9960_Sensor_Arduino_Library/blob/master/examples/ColorSensor/ColorSensor.ino) a try.
