### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [sparkfun/APDS-9960_RGB_and_Gesture_Sensor#24]
In the file "APDS-9960_RGB_and_Gesture_Sensor/Libraries/Arduino/APDS-9960_RGB_and_Gesture_Sensor_Arduino_Library/src/SparkFun_APDS9960.cpp", the function "wireWriteDataBlock()" is not used, but it contains a bug.

The sequence should be: beginTransmission - write - write -write - endTransmission
However, instead of writing data, a Wire.beginTransmission() is called (multiple) times.
At the moment it is at line [2152](https://github.com/sparkfun/APDS-9960_RGB_and_Gesture_Sensor/blob/master/Libraries/Arduino/APDS-9960_RGB_and_Gesture_Sensor_Arduino_Library/src/SparkFun_APDS9960.cpp#L2151).

**Comment by AndyEngland521** [comment]
Good catch, fixed in v1.4.3
