### ISSUE TITLE
setProximityGain has no effect in ProximitySensor.ino example

### ISSUE THREAD

**Issue by wollewald** [sparkfun/APDS-9960_RGB_and_Gesture_Sensor#26]
Changing the PGAIN value in line 61 in the example ProximitySensor.ino has no effect. This is because the enableProximitySensor function (line 66) sets the DEFAULT_PGAIN. Therefore PGAIN changes through setProximityGain needs to be done after enabling the sensor.

**Comment by loricrotser** [comment]
Hi! I'm just now seeing this, but you, sir, are correct. I'll get this fixed here soon. Thanks for the heads up!

**Comment by loricrotser** [comment]
Fixed. Thanks again! 

[Commit 258bea2
](https://github.com/sparkfun/APDS-9960_RGB_and_Gesture_Sensor/commit/258bea2dadc573706ab1e6176f1dea1623e4cffb)
