### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by Altmane** [sparkfun/APDS-9960_RGB_and_Gesture_Sensor#4]
I want to use [Sourcegraph](https://sourcegraph.com) for APDS-9960_RGB_and_Gesture_Sensor code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/sparkfun/APDS-9960_RGB_and_Gesture_Sensor. (It should only take 30 seconds.)

Thank you!

**Comment by ShawnHymel** [comment]
I've never used Sourcegraph, but it sounds really cool. I've added it here: https://sourcegraph.com/github.com/sparkfun/APDS-9960_RGB_and_Gesture_Sensor. Let me know if you have issues with it!
