### ISSUE TITLE
Error with last commit in "GestureTest"

### ISSUE THREAD

**Issue by jcomega** [sparkfun/APDS-9960_RGB_and_Gesture_Sensor#7]
Hi,

The example "GestureTest" doesn't work (For hardware compatibility ) :
because interrupt management is not correct :

_attachInterrupt(0, interruptRoutine, FALLING);_
must be 
_attachInterrupt(APDS9960_INT, interruptRoutine, FALLING);_

and loop() must be : 
_void loop() {
  if( isr_flag == 1 ) {
    detachInterrupt(APDS9960_INT);
    handleGesture();
    isr_flag = 0;
    attachInterrupt(APDS9960_INT, interruptRoutine, FALLING);
  }
}_

**Comment by ShawnHymel** [comment]
This does not work for the popular Arduino boards (Uno, Ethernet, Pro Mini). They have only interrupt numbers 0 and 1 available, so using an interrupt number of 2 would only work for the more powerful boards (e.g. Mega, Due, 32u4-based). For using a different hardware and interrupt number, please refer to https://www.arduino.cc/en/Reference/AttachInterrupt
